# Generated by Django 4.1.5 on 2023-02-25 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_booking_alter_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
